/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.registro;
import javax.swing.JOptionPane;
import modelo.medico;
import modelo.transacciones;
import tipografias.fuentes;

/**
 *
 * @author aishiterushiro
 */
public class ingresar_boleta extends javax.swing.JFrame {

    /**
     * Creates new form ingresar_boleta
     */
    fuentes tipoFuente;

    public ingresar_boleta() {
        initComponents();
                this.setLocationRelativeTo(null);
        tipoFuente =new fuentes();
        jButton1.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jLabel2.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jLabel3.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jLabel4.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar");
        setBackground(new java.awt.Color(242, 242, 242));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel2.setText(" Codigo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 120, 13);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 150, 80, 21);

        jLabel3.setText("Ingresar Codigo Boleta junto con el monto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 100, 390, 30);

        jLabel4.setText(" Monto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 90, 13);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 210, 80, 21);

        jLabel1.setText("Ingresar Boleta.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 330, 70);

        jButton1.setText("Ingresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 250, 360, 40);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 270, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int codigo_trans,monto;
        
        
        try {
            codigo_trans= Integer.parseInt(jTextField1.getText());
            monto = Integer.parseInt(jTextField2.getText());
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en el ingreso", "Validación", JOptionPane.WARNING_MESSAGE);
            jTextField1.setText(" ");
            jTextField2 .setText(" ");   
            
            return;
        }    
        registro rg = new registro();
        if (rg.agregarTrans(new transacciones(codigo_trans,monto)) )  {
            JOptionPane.showMessageDialog(this, "Se agregó transaccion " , "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se agregó transaccion " , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresar_boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresar_boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresar_boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresar_boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresar_boleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
