/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import DB.conexion;
import java.util.ArrayList;

import tipografias.fuentes;
import controlador.registro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.animales;
import modelo.familia;
import modelo.medico;
import modelo.transacciones;
/**
 *
 * @author aishiterushiro
 */
public class listar extends javax.swing.JFrame {

    /**
     * Creates new form listar
     */
    public listar() {
        initComponents();
        this.setLocationRelativeTo(null);
        fuentes tipoFuente;
        tipoFuente = new fuentes();
        jRadioButton1.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jRadioButton2.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jRadioButton3.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jRadioButton4.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));
        jButton1.setFont(tipoFuente.fuente(tipoFuente.NEBULA,0,9));
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 20));
        jButton2.setFont(tipoFuente.fuente(tipoFuente.NEBULA, 0, 9));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 490));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 400));
        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 178, 462, 179);

        jButton1.setText("Listar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 361, 100, 30);

        jLabel1.setText("archivador.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 346, 129);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Animales");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(340, 10, 90, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Familias");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(340, 50, 90, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Medicos");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(340, 90, 90, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Boletas");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(340, 130, 90, 21);

        jButton2.setText("Imprimir");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 360, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/grupo-grande-de-presentacin-de-los-animales-aislado-en-el-fondo-blanco-55938851.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, -60, 290, 360);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       registro rg = new registro();
        jTextArea1.setText("");
    if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected() || jRadioButton4.isSelected() ){
        if (jRadioButton1.isSelected()){
            ArrayList<animales> lista = rg.listar_animales();
            
            for (animales i : lista) {
             
                jTextArea1.append("Codigo: "+i.getCodigoanimal()+"   ");
                jTextArea1.append("Nombre: "+i.getNombre()+"   ");
                jTextArea1.append("Tipo: "+i.getTipo()+"   ");
                jTextArea1.append("Edad: "+i.getEdad()+"   ");
                jTextArea1.append("Raza: "+i.getRaza()+"   ");
                jTextArea1.append("Diagnostico: "+ i.getDiagnostico()+"   "+"\n");
               
                
           
        
        }
        }
        if (jRadioButton2.isSelected()){
            ArrayList<familia> lista = rg.listar_familia();
            for (familia i : lista) {
             
                jTextArea1.append("Codigo familia: " + i.getCodigofamilia()+"   ");
                jTextArea1.append("Apellido Paterno: " + i.getApellidoP()+"   ");
                jTextArea1.append("Apellido Materno: " + i.getApellidoM()+"   ");
                jTextArea1.append("Telefono: " + i.getTelefono()+"   ");
                jTextArea1.append("Correo electronico: " + i.getCorreoelectronico()+"   "+"\n");
           
        
        }
        }
        if (jRadioButton3.isSelected()){
            ArrayList<medico> lista = rg.listar_medico();
            for (medico i : lista) {
             
                jTextArea1.append("Codigo medico: " + i.getCodigomedico()+"   ");
                jTextArea1.append("Nombre: " + i.getNombre()+"   ");
                jTextArea1.append("Apellido: " + i.getApellido()+"   ");
                jTextArea1.append("Especialidad: " + i.getEspecialidad()+"   "+"\n");
        }
        }
        if (jRadioButton4.isSelected()){
        ArrayList<transacciones> lista = rg.listar_transacciones();
            for (transacciones i : lista) {
             
                jTextArea1.append("Codigo transaccion: " + i.getCodigo_trans()+"   ");
                jTextArea1.append("Monto: " + i.getMonto()+"   "+"\n");
        }}}
    else JOptionPane.showMessageDialog(this, "Seleccione una opcion a listar", "Importante!!", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
